<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Python Coding Exercise 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**
6. **[Data Structures with Examples](#Data_Structures)**
7. **[Create and Manipulate the DataFrames](#create_manipulate)**
8. **[Sort](#sorting)**
9. **[Rank](#ranking)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [3]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
wt_80 = []
for wt in weights:
    if wt >80:
        wt_80.append(wt)

print(wt_80)

[85, 86, 82]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [8]:
# type your code here
import numpy as np
ar1 = np.random.randint(low = 20, high =40, size=10)
ar1

array([24, 24, 25, 25, 24, 23, 23, 37, 37, 34])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [22]:
# type your code here
lst = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
t = 0 
def nested_sum(L):
    total = 0   
    for i in L:
        if isinstance(i, list):   
            total += nested_sum(i)
        else:
            total += i
    return total
t = nested_sum(lst)
print(t)

53


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [26]:
# type your code here
ar1 = np.random.randint(low = 20, high =50, size=20)
ar1
B = np.reshape(ar1, (-1, 2))
B

array([[44, 35],
       [33, 23],
       [31, 48],
       [46, 29],
       [38, 23],
       [46, 48],
       [24, 38],
       [47, 43],
       [40, 44],
       [21, 43]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [29]:
# type your code here
weights = [57, 69, 54, 65 ,71, 62, 56]

#list of heights (in m)<br>
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]
#the_BMI = the_weight / (the_height)**2  
list3 = [  m/(n)**2 for m,n in zip(weights,heights)]
print(list3)

[22.54657648036074, 22.53061224489796, 19.5964581216432, 21.469150482230148, 26.397977394408095, 20.9572742022715, 23.92242299970097]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [31]:
# type your code here
array1 = [[[3, 4], [8, 2],[5, 9]]]
array1.append([5,7])
array1

[[[3, 4], [8, 2], [5, 9]], [5, 7]]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [33]:
# type your code here
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

for i in range(len(M)):
   # iterate through columns
   for j in range(len(M[0])):
        result[j][i] = M[i][j]

for r in result:
    print(r)

[15, 7, 54, 0]
[17, 42, 3, 87]
[45, 15, 61, 16]
[56, 63, 41, 20]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [35]:
# type your code here
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]
#A1+A2 [[5, 9], [7, 6], [8, -7], [0, 4]]
result_array = np.vstack((A1, A2))
result_array



array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [36]:
# type your code here
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]
result_array = np.hstack((A1, A2))
result_array


array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [41]:
# type your code here
B =  np.arange(16).reshape(4, 4)
print("\nOriginal arrays:")
print(B)
new_array1 = np.vsplit(B, 2)
print("\nSplit :")
print(new_array1)


Original arrays:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split :
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [43]:
# type your code here
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]
l3 = list(map(lambda x, y: str(x)+ ' ' +str(y), L1, L2))
l3


['45 21', '67 52', '56 64', '71 10', '54 49', '62 74', '56 26']

<a id='Data_Structures'></a>
## 6. Data Structures with Examples:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to create a dataframe from list of lists
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below nested list:**<br>

        data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

In [45]:
# type your code here
import pandas as pd
data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]
df = pd.DataFrame(data)
df


0   1
0  Joy  21
1  Mia  15
2  Sam  14

<a id='create_manipulate'></a>
## 7. Create and Manipulate the DataFrames:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Split the 'Name' column into two separate columns as First_Name and Last_Name </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Salary</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>3200</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>4500</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>3600</td>
</tr>
<tr>
<td>James Smith</td>
<td>5596</td>
</tr>
   
</table>

In [53]:
# type your code here
 


data = [['Emma Larter', 3200], ['Mia Junior', 4500], ['Sophia Depp', 3600], ['James Smith',5596]]
user_df = pd.DataFrame(data, columns=['Name', 'Salary'])
print(user_df)

user_names = user_df['Name'].str.split(pat = ' ', expand = True)

user_df[['first_name', 'last_name']] = user_names
print(user_df)

          Name  Salary
0  Emma Larter    3200
1   Mia Junior    4500
2  Sophia Depp    3600
3  James Smith    5596
          Name  Salary first_name last_name
0  Emma Larter    3200       Emma    Larter
1   Mia Junior    4500        Mia    Junior
2  Sophia Depp    3600     Sophia      Depp
3  James Smith    5596      James     Smith


In [58]:
# Rename Name to given Name 
user_df.rename(columns= {'Name': 'Given_Name'}, inplace=True)
user_df

Given_Name  Salary first_name last_name
0  Emma Larter    3200       Emma    Larter
1   Mia Junior    4500        Mia    Junior
2  Sophia Depp    3600     Sophia      Depp
3  James Smith    5596      James     Smith

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to select the rows where the sales are higher than 60000 for Mumbai </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [64]:
# type your code here  
data = {'Store': ['A', 'B', 'A', 'C','D', 'A', 'D', 'A','C', 'B'],
        'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai','Pune', 'Delhi', 'Hyderabad', 'Pune','Mumbai', 'Pune'],
        'Sales': [ 40000,45000 ,50000, 90000,89000,87000,85000,78000,89000,70000] }
df = pd.DataFrame(data)
df

Store   Location  Sales
0     A     Mumbai  40000
1     B       Pune  45000
2     A  Hyderabad  50000
3     C     Mumbai  90000
4     D       Pune  89000
5     A      Delhi  87000
6     D  Hyderabad  85000
7     A       Pune  78000
8     C     Mumbai  89000
9     B       Pune  70000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a program to replace the 'Store' column with the values A, B, C, and D with Store_A,  Store_B, Store_C and Store_D respectively </b>  
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [65]:
# type your code here
#df['Store'] = (df['First Season'] > 1990).astype(int)
df['Store'] = 'Store_'+df['Store']
df

Store   Location  Sales
0  Store_A     Mumbai  40000
1  Store_B       Pune  45000
2  Store_A  Hyderabad  50000
3  Store_C     Mumbai  90000
4  Store_D       Pune  89000
5  Store_A      Delhi  87000
6  Store_D  Hyderabad  85000
7  Store_A       Pune  78000
8  Store_C     Mumbai  89000
9  Store_B       Pune  70000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a program to insert a given column at the second position in a dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
   
</table>

**Add the variable 'Salary' as second column**<br>
            
            Salary = [35000, 24000, 55000, 40000]

In [71]:
# type your code here

data = [['Emma Larter', 34], ['Mia Junior', 59], ['Sophia Depp', 32], ['James Smith',40]]
df1 = pd.DataFrame(data, columns=['Name', 'Age'])
print(df1)
Salary = [35000, 24000, 55000, 40000]
df1.insert(1, 'Salary', Salary)
print(df1)

          Name  Age
0  Emma Larter   34
1   Mia Junior   59
2  Sophia Depp   32
3  James Smith   40
          Name  Salary  Age
0  Emma Larter   35000   34
1   Mia Junior   24000   59
2  Sophia Depp   55000   32
3  James Smith   40000   40


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to get the third observation of the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
</table>    

In [72]:
# type your code here
data = [['Emma Larter', 34], ['Mia Junior', 59], ['Sophia Depp', 32], ['James Smith',40]]
df2 = pd.DataFrame(data, columns=['Name', 'Age'])
print(df2)
df2.iloc[2:3] 

          Name  Age
0  Emma Larter   34
1   Mia Junior   59
2  Sophia Depp   32
3  James Smith   40


Name  Age
2  Sophia Depp   32

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to count total sales per store </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [86]:
# type your code here
data_store = {'Store': ['A', 'B', 'A', 'C','D', 'A', 'D', 'A','C', 'B'],
        'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai','Pune', 'Delhi', 'Hyderabad', 'Pune','Mumbai', 'Pune'],
        'Sales': [ 40000,45000 ,50000, 90000,89000,87000,85000,78000,89000,70000] }
df_store = pd.DataFrame(data_store)
df_store
new = df_store.groupby('Store')['Sales'].sum()
display(new)

Store
A    255000
B    115000
C    179000
D    174000
Name: Sales, dtype: int64

<a id='sorting'></a>
## 8. Sort

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Write a program to sort the dataframe by 'Store' in ascending order and by 'Sales' in descending order simultaneously
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [89]:
# type your code here
data_store1 = {'Store': ['A', 'B', 'A', 'C','D', 'A', 'D', 'A','C', 'B'],
        'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai','Pune', 'Delhi', 'Hyderabad', 'Pune','Mumbai', 'Pune'],
        'Sales': [ 40000,45000 ,50000, 90000,89000,87000,85000,78000,89000,70000] }
df_store1 = pd.DataFrame(data_store1)
df_store1
df_store1.sort_values(['Store', 'Sales'], ascending=[True, False])

Store   Location  Sales
5     A      Delhi  87000
7     A       Pune  78000
2     A  Hyderabad  50000
0     A     Mumbai  40000
9     B       Pune  70000
1     B       Pune  45000
3     C     Mumbai  90000
8     C     Mumbai  89000
4     D       Pune  89000
6     D  Hyderabad  85000

<a id='ranking'></a>
## 9. Rank

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Rank the dataframe in descending order of sales by each store
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [91]:
# type your code here
data_store2 = {'Store': ['A', 'B', 'A', 'C','D', 'A', 'D', 'A','C', 'B'],
        'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai','Pune', 'Delhi', 'Hyderabad', 'Pune','Mumbai', 'Pune'],
        'Sales': [ 40000,45000 ,50000, 90000,89000,87000,85000,78000,89000,70000] }
df_store2= pd.DataFrame(data_store2)
df_store2['Ranked_sale']= df_store2['Sales'].rank(ascending=False)
df_store2

Store   Location  Sales  Ranked_sale
0     A     Mumbai  40000         10.0
1     B       Pune  45000          9.0
2     A  Hyderabad  50000          8.0
3     C     Mumbai  90000          1.0
4     D       Pune  89000          2.5
5     A      Delhi  87000          4.0
6     D  Hyderabad  85000          5.0
7     A       Pune  78000          6.0
8     C     Mumbai  89000          2.5
9     B       Pune  70000          7.0